#!/bin/bash

WORK_DIR=`pwd`
BUILD_DIR=`pwd`"/Build"
TEST_DIR=`pwd`"/Test"

# Argument parsing from
# https://stackoverflow.com/questions/192249
POSITIONAL=()
KEY="${1}"
while [[ $# -gt 0 ]]; do
    case ${KEY} in
        -h|--help)
            HELP=true
            shift
            ;;
        -c|--clean)
            CLEAN=true
            shift
            ;;
        -t|--test)
            TEST=true
            shift
            ;;
         *)
            POSITIONAL+=("${1}")
            shift
            ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [ "${HELP}" = true ]; then
    echo "Usage: ./Make [-h, -c, -t]"
    echo
    echo "      -h, --help   Show this help"
    echo "      -c, --clean  Clean build directory"
    echo "      -t, --test   Test the library"
    exit
fi

if [ "${CLEAN}" == true ]; then
  echo "INFO: Cleaning \"${BUILD_DIR}\" directory..."
  rm -rf ${BUILD_DIR}/*
  exit
fi

echo "INFO: Building..."

if [ ! -d "${BUILD_DIR}" ]; then
  echo "WARNING: Build directory \"${BUILD_DIR}\" does not exist, creating it."
  mkdir ${BUILD_DIR}
fi
cd ${BUILD_DIR}

if [ -x "$(command -v cmake)" ]; then
  cmake ${WORK_DIR}
else
  echo "WARNING: \"cmake\" not found, trying \"cmake3\"."
  cmake3 ${WORK_DIR}
fi

make
SUCCESS=$?

if [ ${SUCCESS} -eq 0 ] && [ "${TEST}" == true ]; then
  echo "INFO: Testing..."
  cp ${BUILD_DIR}/Test ${TEST_DIR}/
  cd ${TEST_DIR}
  ./Test
fi

exit ${SUCCESS}
